
/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW [dbo].[vwFactPlayerShots] AS 
(
SELECT [player_id]
      ,[minute]
      ,[game_play_key]
      ,[shot_type_key]
      ,[outcome_key]
      ,[x_cord]
      ,[y_cord]
      ,[xG]
      ,[assisted_by]
      ,[action_key]
      ,[match_id]
      ,[home_away]
      ,[event_id]
	  ,'Bundesliga' [league]
      ,[year]
  FROM [bundesliga].[factPlayerShots]

  UNION ALL

  SELECT [player_id]
      ,[minute]
      ,[game_play_key]
      ,[shot_type_key]
      ,[outcome_key]
      ,[x_cord]
      ,[y_cord]
      ,[xG]
      ,[assisted_by]
      ,[action_key]
      ,[match_id]
      ,[home_away]
      ,[event_id]
	  ,'EPL' [league]
      ,[year]
  FROM [epl].[factPlayerShots]

    UNION ALL

  SELECT [player_id]
      ,[minute]
      ,[game_play_key]
      ,[shot_type_key]
      ,[outcome_key]
      ,[x_cord]
      ,[y_cord]
      ,[xG]
      ,[assisted_by]
      ,[action_key]
      ,[match_id]
      ,[home_away]
      ,[event_id]
	  ,'LaLiga' [league]
      ,[year]
  FROM [laliga].[factPlayerShots]

    UNION ALL

  SELECT [player_id]
      ,[minute]
      ,[game_play_key]
      ,[shot_type_key]
      ,[outcome_key]
      ,[x_cord]
      ,[y_cord]
      ,[xG]
      ,[assisted_by]
      ,[action_key]
      ,[match_id]
      ,[home_away]
      ,[event_id]
	  ,'Ligue1' [league]
      ,[year]
  FROM [ligue1].[factPlayerShots]

    UNION ALL

  SELECT [player_id]
      ,[minute]
      ,[game_play_key]
      ,[shot_type_key]
      ,[outcome_key]
      ,[x_cord]
      ,[y_cord]
      ,[xG]
      ,[assisted_by]
      ,[action_key]
      ,[match_id]
      ,[home_away]
      ,[event_id]
	  ,'RFPL' [league]
      ,[year]
  FROM [rfpl].[factPlayerShots]

    UNION ALL

  SELECT [player_id]
      ,[minute]
      ,[game_play_key]
      ,[shot_type_key]
      ,[outcome_key]
      ,[x_cord]
      ,[y_cord]
      ,[xG]
      ,[assisted_by]
      ,[action_key]
      ,[match_id]
      ,[home_away]
      ,[event_id]
	  ,'SerieA' [league]
      ,[year]
  FROM [seriea].[factPlayerShots]
  )
  
